version: "3.6"

services:
  web:
    image: "${IMAGE_NAME}:latest"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    restart: always
    ports:
      - "80:80"
    networks:
      apps:
    links:
      - db
      - server
    depends_on:
      - db
      - server

  server:
    image: "${IMAGE_NAME_BACKEND}:latest"
    environment:
      PORT: "80"
      DATABASE: "http://admin:${DB_PASSWORD}@db:5984"
    restart: always
    links:
      - db
      - logstash
    volumes:
      - type: bind
        source: ./secret.key
        target: /app/secret.key
        read_only: false
    depends_on:
      - db
      - logstash
    networks:
      apps:

  db:
    image: couchdb:3.3.2
    environment:
      COUCHDB_USER: admin
      COUCHDB_PASSWORD: "${DB_PASSWORD}"
    restart: always
    networks:
      apps:
    volumes:
      - couchdb_data:/opt/couchdb/data
      - ./couchdb.ini:/opt/couchdb/etc/local.ini

  elasticsearch:
    image: elasticsearch:7.16.1
    environment:
      discovery.type: single-node
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
    volumes:
      - elastic_data:/usr/share/elasticsearch/data:rw
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail localhost:9200/_cluster/health || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 3
    networks:
      - elastic

  logstash:
    image: logstash:7.16.1
    environment:
      discovery.seed_hosts: logstash
      LS_JAVA_OPTS: "-Xms512m -Xmx512m"
      ELASTIC_PASSWORD: ELASTIC_PASSWORD
    restart: always
    volumes:
      - ./logstash.config:/usr/share/logstash/pipeline/logstash-nginx.config:ro
    depends_on:
      - elasticsearch
    networks:
      - elastic
      - apps
    command: logstash -f /usr/share/logstash/pipeline/logstash-nginx.config

volumes:
  couchdb_data:
  elastic_data:

networks:
  elastic:
    driver: bridge
  apps:
    driver: bridge
