name: Docker Deploy

on:
  push:
    branches:
      - 'main'

jobs:
  deploy:
    runs-on: [self-hosted, acsrv]
    steps:
      - uses: actions/checkout@v3
      - name: run image
        run: docker-compose up -d
      - name: cleanup docker containers
        run: docker container prune --filter "until=24h" -f
      - name: cleanup docker images
        run: docker image prune -a -f --filter "until=24h"
